apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: services
  labels:
    app: api-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 8080
  type: ClusterIP
