apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - api-ingress.yaml

patches:
  - target:
      kind: Deployment
      name: api-deployment
    path: api-deployment-patch.yaml
