---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  generation: 2
  name: alert-info
  namespace: flux-system
spec:
  providerRef:
    name: slack
  eventSeverity: info
  eventMetadata:
    environment: prod
  eventSources:
    - kind: HelmRepository
      name: "*"
    - kind: ImagePolicy
      name: "*"
