apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: production-cert
  namespace: services
spec:
  secretName: tls-production-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - rmzgpt.leets.app
