name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: intall nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 18.18.0

      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.0

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: typecheck
        run: pnpm typecheck

  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: intall nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 18.18.0

      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.0

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Generate Prisma Client
        run: pnpm generate
        working-directory: ./apps/api

      - name: test
        run: pnpm test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: intall nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 18.18.0

      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.0

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: typecheck
        run: pnpm build
  deploy-db:
    name: Deploy db
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-group
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.2.0

      - name: Install pnpm and dependencies
        run: |
          npm install -g pnpm
          pnpm install --no-frozen-lockfile
        working-directory: ./apps/api

      - name: Run migrations
        run: pnpm migrate
        working-directory: ./apps/api
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
