name: Fly Deploy

on:
  pull_request:

jobs:
  deploy-web:
    name: Deploy web
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: echo VITE_API_URL=$API_URL > ./apps/front/.env
        env:
          API_URL: ${{ secrets.VITE_API_URL }}

      - run: flyctl deploy --dockerfile ./apps/front/Dockerfile --config ./apps/front/fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_FRONT_TOKEN }}
