name: Deploy 🚀

on:
  workflow_run:
    workflows: [CI]
    branches: [main]
    types:
      - completed

jobs:
  deploy-api:
    name: Deploy api
    runs-on: ubuntu-latest

    concurrency:
      group: deploy-group
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --dockerfile ./apps/api/Dockerfile --config ./apps/api/fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-front:
    name: Deploy web
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-group
      cancel-in-progress: true
    needs: deploy-api
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: echo VITE_API_URL=$API_URL > ./apps/front/.env
        env:
          API_URL: ${{ secrets.VITE_API_URL }}

      - run: flyctl deploy --dockerfile ./apps/front/Dockerfile --config ./apps/front/fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_FRONT_TOKEN }}

  deploy-db:
    name: Deploy db
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-group
      cancel-in-progress: true
    needs: deploy-api
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.2.0

      - name: Install pnpm and dependencies
        run: |
          npm install -g pnpm
          pnpm install --no-frozen-lockfile
        working-directory: ./apps/api

      - name: Run migrations
        run: pnpm run migrate
        working-directory: ./apps/api
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
