apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      automountServiceAccountToken: false
      containers:
        - name: frontend
          image: 222634381307.dkr.ecr.eu-west-1.amazonaws.com/rmzgpt/front:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "512Mi"
              ephemeral-storage: "2Gi"
            requests:
              memory: "256Mi"
              cpu: "250m"
              ephemeral-storage: "1Gi"
      imagePullSecrets:
        - name: regcred
